import React, { Component } from 'react'
import styles from './Body.scss'

export default class Body extends Component{
    render(){
        return(
            <div className={styles.bodyContainer}>
                <div className={styles.bodyLeft}>
                    <div className={styles.topLeft}>
                        <div className={styles.avatarContainer}></div>
                        <div className={styles.uploadStats}></div>
                    </div>
                    <div className={styles.uploadForm}>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas a neque nibh. Ut a diam at tortor consequat cursus nec nec risus. Integer hendrerit, sem a maximus posuere, risus erat sagittis sem, nec hendrerit ipsum mi id risus. Sed tempus felis venenatis quam accumsan faucibus. Nullam luctus vel sapien ut scelerisque. Phasellus tempor nulla quis magna tincidunt, at consectetur orci vestibulum. Fusce at volutpat leo. Fusce in dui placerat, finibus nisi eu, rutrum enim. Integer lacinia feugiat ante eu ultricies. Etiam non lorem malesuada, laoreet mauris convallis, cursus dolor. Sed pulvinar metus est. Ut ac felis sit amet lorem luctus congue. Duis accumsan urna et felis aliquam, eget viverra lacus accumsan. Praesent eros eros, suscipit ac nibh quis, fermentum scelerisque ante.

Cras molestie augue id elementum facilisis. Maecenas interdum sed purus et porttitor. Aliquam erat volutpat. Duis eget bibendum augue, a pretium ipsum. Aliquam et urna dictum, consequat augue at, gravida ex. Mauris volutpat risus felis, ut vehicula ligula imperdiet ut. Praesent et efficitur risus. Morbi volutpat ipsum non leo varius mollis. Phasellus ultrices elementum nisi, vel molestie felis sodales quis. Mauris ultrices nisi vel magna dapibus tristique. Cras ut risus tortor.

Duis interdum vehicula leo vitae auctor. Mauris volutpat elementum est aliquet porttitor. Vivamus auctor sapien nec tincidunt tincidunt. Donec mattis, lorem in maximus iaculis, odio ante ultrices dui, eu faucibus nisl lacus vitae nunc. Nam elementum quam sem, at gravida tellus gravida sed. Sed quis auctor ante. Nam placerat, massa non consequat placerat, libero sem mattis lectus, non vulputate elit nunc ut velit. Phasellus pulvinar massa in iaculis hendrerit. Sed vestibulum sit amet dolor et interdum. Pellentesque pretium, ex ac congue maximus, ante diam placerat mi, nec maximus nisi ligula nec sem. Donec vehicula orci a erat vehicula tristique. Pellentesque at condimentum eros.

Nulla sit amet nulla id massa viverra ornare. Vivamus non tortor in nunc accumsan dictum ut vel est. Praesent a ipsum quis arcu lacinia mattis. Etiam ornare varius dui tempus volutpat. Quisque pharetra ultricies tempus. Mauris facilisis dapibus risus hendrerit pharetra. Maecenas nisi arcu, faucibus a neque non, feugiat mollis orci. In pharetra nunc erat, id pulvinar tortor hendrerit eu. Fusce at ornare tortor, a luctus risus. Nulla tristique ligula at justo pharetra mattis et vel ligula. Nunc aliquet malesuada leo id tristique. Nulla auctor lectus quis dui porttitor, nec auctor metus commodo. Suspendisse at mauris elementum, faucibus tortor ac, convallis purus. Nunc tempor leo non eros suscipit dignissim. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Mauris arcu lectus, pharetra nec dignissim ut, sodales sed ligula. Sed ultrices, lacus at finibus blandit, ligula nulla feugiat nisi, id feugiat sem nibh egestas ex. In sit amet dui mi. Curabitur ex ex, pellentesque quis aliquet bibendum, auctor eu enim. Pellentesque nec fringilla leo, et dignissim libero. Duis aliquam quis augue eget suscipit. Sed ac ligula dolor. Nunc bibendum lacus ipsum.

Nullam efficitur a odio non aliquet. Fusce consectetur dapibus orci, at cursus leo sollicitudin a. Suspendisse dapibus mi vitae ligula aliquet rutrum. Morbi nisi elit, euismod nec tortor eget, tincidunt egestas neque. Donec finibus, lacus sit amet facilisis aliquam, risus lectus interdum erat, vitae elementum diam elit in nulla. Suspendisse at imperdiet lectus. In at lorem at eros facilisis dapibus eget et massa.

Phasellus vel bibendum risus. Ut tincidunt eleifend mi, in viverra justo semper eu. Fusce gravida tellus vitae nisl scelerisque, eget feugiat lorem auctor. Duis eget justo eget ligula consequat gravida et sed nisl. Donec sit amet imperdiet velit, et efficitur turpis. Suspendisse non metus libero. Suspendisse nec diam non justo commodo tincidunt ac ac nulla. In eget urna nibh. Aenean cursus felis turpis, ac porttitor neque iaculis quis. Aliquam feugiat elementum nisl quis blandit. In imperdiet ipsum non ipsum fringilla, in egestas erat ullamcorper. Etiam eleifend malesuada laoreet. Nunc auctor tempor pulvinar. Cras rhoncus aliquam porttitor. Nam quis volutpat nulla.

Maecenas quis gravida odio. Sed faucibus justo sed tincidunt congue. Mauris luctus feugiat metus, at commodo lectus rutrum interdum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus pharetra congue pharetra. Ut vitae purus eu dui malesuada porttitor ac eget nisi. Sed consequat lobortis orci vel vehicula. Cras eget ipsum tempor ipsum rhoncus lacinia id at diam. Praesent bibendum rhoncus nulla, at feugiat neque vulputate sed. Etiam molestie metus at mauris faucibus sagittis. Fusce justo sem, varius id vulputate ut, vulputate nec dolor. Aliquam massa tortor, sagittis non auctor vitae, lobortis ac sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit.

Quisque et porta ex. Vivamus nec finibus mi. Mauris varius vel odio a gravida. Quisque congue ut tortor sit amet mattis. Phasellus ultricies pellentesque nulla in dapibus. Sed mollis egestas elit. Vivamus vehicula urna ut magna posuere, non mattis arcu auctor. Quisque nec tincidunt nisi, semper suscipit urna. Donec lectus lectus, semper rhoncus vestibulum vitae, facilisis vitae nunc. Praesent auctor scelerisque vehicula. Etiam cursus elementum metus, sed commodo ipsum suscipit ut. Nam varius mollis odio ut dapibus. Nulla vitae felis ligula. Sed tempor iaculis quam, eget sagittis metus accumsan nec. Integer non aliquam tellus.

In elementum in nunc et vulputate. Aliquam semper lorem ac est dictum, quis tempor quam tempor. Donec vitae ante ullamcorper, bibendum magna non, scelerisque tellus. Quisque nec placerat elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vel metus luctus, eleifend massa et, volutpat odio. Praesent sagittis diam ut urna iaculis elementum. Quisque mollis elit quam, id vestibulum urna facilisis sit amet. Curabitur sit amet aliquet arcu, non porttitor diam. Sed maximus euismod enim eget sodales. Suspendisse in ligula nec turpis porta imperdiet in sit amet urna. Nunc vel tortor ut purus sodales convallis. Quisque eros ex, scelerisque non neque eu, faucibus accumsan velit. Nunc dictum lectus et est dapibus, nec interdum libero dignissim.

Sed ligula tortor, tincidunt quis aliquet et, fermentum imperdiet mi. Quisque at dolor commodo, convallis mauris ac, bibendum ex. Pellentesque consequat dictum sem, vel faucibus lacus tincidunt in. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam at nulla ut libero fermentum ornare. Cras maximus suscipit hendrerit. Maecenas rhoncus luctus felis, sed finibus est eleifend non. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris elit dui, ultrices nec luctus at, cursus vel diam. Fusce nec mauris ac nibh convallis dictum. Vivamus vulputate tortor vitae nulla vulputate efficitur.

Morbi velit nulla, tincidunt vel consequat nec, hendrerit nec diam. Cras cursus orci sit amet orci egestas sodales. Nunc dapibus lectus ut sem scelerisque egestas. Nunc faucibus luctus facilisis. Vestibulum at maximus velit. Vivamus eget sagittis leo. Proin tempus hendrerit nulla vitae feugiat. Proin et laoreet quam. Nullam quis velit orci. Praesent suscipit tortor in sapien pellentesque mattis. Curabitur nec mauris quis diam facilisis efficitur. Praesent at porttitor nisi. Nullam porta mi turpis, vitae eleifend nisi tempor vel.

Quisque aliquet ante eget libero aliquet facilisis. Phasellus at magna odio. Cras posuere, nisi sed euismod ultricies, nisl orci luctus tellus, eget rutrum elit est vel lorem. Duis eu egestas turpis. Aenean bibendum diam ut nisl pulvinar hendrerit. Quisque dapibus a urna in interdum. Quisque eget sagittis orci. Aliquam ut magna urna. Integer at arcu facilisis, aliquam purus vitae, vestibulum libero. Vestibulum condimentum ipsum quis pretium pellentesque. In at nulla dolor. Nulla condimentum ac quam sit amet vulputate. Donec egestas placerat diam, vitae sodales ligula.

Nulla pretium enim et dolor scelerisque, sed varius nulla convallis. Nam eu est porta, rutrum lectus vitae, ultrices urna. Fusce non risus ac odio viverra vulputate. Etiam risus est, posuere eget tempor congue, tempus finibus metus. Donec sapien tellus, suscipit nec faucibus egestas, porta ac ante. Ut a elit pharetra, molestie odio eu, facilisis urna. Suspendisse id cursus magna. Proin mauris ipsum, viverra sit amet tortor ut, facilisis accumsan ante.

Ut commodo a lacus ut efficitur. Etiam suscipit, nibh quis bibendum sagittis, augue orci rhoncus metus, quis maximus arcu lectus quis tellus. Morbi maximus lectus ac auctor dapibus. Donec laoreet dignissim neque non posuere. Suspendisse potenti. Suspendisse lobortis aliquet magna et gravida. Nam maximus fringilla eleifend. Mauris non nulla dapibus, gravida lectus vitae, dictum mi. Phasellus at dolor non turpis scelerisque feugiat. Duis cursus placerat nisi, eu consectetur nisl fringilla non. Suspendisse pellentesque, ex non tincidunt pulvinar, sem nulla dignissim nisi, et facilisis odio tortor id nisl. Ut auctor est nisl, a sagittis arcu interdum quis. Sed lacus quam, tempus vel elementum ut, feugiat aliquam sapien. Pellentesque odio augue, tristique ac vehicula at, faucibus ut elit.</div>
                </div>
                <div className={styles.bodyRight}>
                    <div className={styles.uploadsContainer}></div>
                </div>
            </div>
        )
    }
}